[theme]
base = "light"
primaryColor = "#6B0B0C"            # Rosewood  -> tombol, slider, radio, tab aktif
backgroundColor = "#FFFFFF"         # halaman utama putih
secondaryBackgroundColor = "#FFFBE3" # krem lembut (turunan Lemon Chiffon) -> input, kode, sidebar
textColor = "#2D120D"               # Coffee Bean -> teks utama (kontras 17:1 di putih)
font = "sans serif"
